### ISSUE TITLE
Issue with gadicc:ecmascript-hot?

### ISSUE THREAD

**Issue by kokjinsam** [tomitrescak/meteor-mantra-redux-graphql#1]
hey @tomitrescak , I see that you're using `gadicc:ecmascript-hot` and `apollo`. I wonder if you have encountered any problems like mine [here](https://github.com/gadicc/meteor-hmr/issues/92#issuecomment-220806460). I'm aware that you had similar [issue](https://github.com/apollostack/apollo-client/issues/216) but the cause was different.

**Comment by tomitrescak** [comment]
No, not really:/ all works fine when I get rid of typescript :/

**Comment by kokjinsam** [comment]
hey, thanks for telling me. I think I found the culprit: `babel-plugin-transform-async-to-generator` in `babel-preset-stage-0`.

**Comment by tomitrescak** [comment]
So how did you solve it? Would be interesting to know

**Comment by kokjinsam** [comment]
I removed `babel-preset-stage-0` and manually added back everything in the preset except `babel-plugin-transform-async-to-generator` and `babel-plugin-syntax-async-to-generator`. I think Meteor 1.3 handles async / await for us already.
