### ISSUE TITLE
"git checkout hot"?

### ISSUE THREAD

**Issue by VikR0001** [tomitrescak/meteor-mantra-redux-graphql#3]
The readme says:

> (don't forget to git checkout hot)

I haven't encountered a command of this name yet. A google search for "git checkout hot" brings up this link as the top search result:

> https://git-scm.com/docs/git-checkout

...but this page does not seem to contain the word "hot".  A search for "what is git checkout hot" also doesn't seem to bring up anything defining a command "git checkout hot".

What is the correct way to perform git checkout hot when cloning and/or using this repo?

Thanks very much in advance for the info.

**Comment by tomitrescak** [comment]
Vik. Sorry, the README comes from the mantra-hot-loader project. Just ignore that. I'll remove it.

**Comment by VikR0001** [comment]
Thanks very much for this info!
